name: f4
description: A set of Future helper functions (mostly) compatible with Node.js counterpart Promise libraries such as Bluebird. Supports concurrency & cancellation.
version: 1.0.1
homepage: https://github.com/1N50MN14/f4
author: 1N50MN14 <ayman.mackouly@gmail.com>

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  meta: ^1.1.7

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
